#!/bin/bash

echo "🚀 Truth-Detector Deployment Script"
echo "======================================"
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}Step 1: Pushing code to GitHub...${NC}"
echo ""
echo "Repository: https://github.com/zunnoonwaheed/AI-News-Fact-Checker"
echo ""
echo "If prompted for credentials:"
echo "  Username: zunnoonwaheed"
echo "  Password: Use your GitHub Personal Access Token"
echo ""
echo "Get token here: https://github.com/settings/tokens/new"
echo "(Select 'repo' scope and copy the token)"
echo ""

git push -u origin main

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✅ Code pushed successfully!${NC}"
    echo ""
    echo -e "${BLUE}Step 2: Deploy to Vercel${NC}"
    echo "========================================"
    echo ""
    echo "1. Go to: https://vercel.com/new"
    echo "2. Click 'Import' next to 'AI-News-Fact-Checker'"
    echo "3. Configure the build:"
    echo "   - Build Command: PORT=5173 BASE_PATH=/ pnpm run build"
    echo "   - Output Directory: artifacts/fact-checker/dist/public"
    echo "   - Install Command: pnpm install"
    echo ""
    echo "4. Add Environment Variables:"
    echo "   - VITE_API_URL (we'll set this after backend deploys)"
    echo "   - PORT: 5173"
    echo "   - BASE_PATH: /"
    echo ""
    echo "5. Click 'Deploy' and wait..."
    echo ""
    echo -e "${BLUE}Step 3: Deploy Backend to Render${NC}"
    echo "========================================"
    echo ""
    echo "1. Go to: https://render.com/create"
    echo "2. Select 'Web Service'"
    echo "3. Connect your GitHub: AI-News-Fact-Checker"
    echo "4. Configuration:"
    echo "   - Name: truth-detector-api"
    echo "   - Build Command: cd artifacts/api-server && pnpm install && pnpm run build"
    echo "   - Start Command: cd artifacts/api-server && pnpm run start"
    echo ""
    echo "5. Environment Variables:"
    echo "   DATABASE_URL=postgresql://... (get from Neon.tech)"
    echo "   GROQ_API_KEY=your_groq_key"
    echo "   NEWS_API_KEY=99a71cbc53ab4f62b7fed672fb69b47c"
    echo "   NODE_ENV=production"
    echo "   PORT=3000"
    echo ""
    echo "6. Click 'Create Web Service'"
    echo ""
    echo -e "${BLUE}Step 4: Set up Database on Neon${NC}"
    echo "========================================"
    echo ""
    echo "1. Go to: https://neon.tech"
    echo "2. Sign up (free tier)"
    echo "3. Create a new project"
    echo "4. Copy the connection string"
    echo "5. Add it to Render as DATABASE_URL"
    echo ""
    echo -e "${BLUE}Step 5: Update Vercel with Backend URL${NC}"
    echo "========================================"
    echo ""
    echo "1. After Render deploys, copy the URL (e.g., https://truth-detector-api.onrender.com)"
    echo "2. Go to Vercel project settings"
    echo "3. Add VITE_API_URL environment variable with the Render URL"
    echo "4. Redeploy the frontend"
    echo ""
    echo -e "${GREEN}✨ That's it! Your app will be live!${NC}"
    echo ""
else
    echo -e "${YELLOW}⚠️  Push failed. Please check your credentials.${NC}"
    echo ""
    echo "Make sure you:"
    echo "1. Created a Personal Access Token: https://github.com/settings/tokens/new"
    echo "2. Selected 'repo' scope"
    echo "3. Used the token as password (not your GitHub password)"
fi
